parameters:
    xhprof.store.profiling.controller.class: Xhprof\StoreBundle\Controller\ProfilingController

services:
    xhprof.store.profiling.controller:
        class: "%xhprof.store.profiling.controller.class%"