parameters:
    xhprof.profiling.save.handler.class: Xhprof\StoreBundle\Services\ProfilingSaveHandler
    xhprof.profiling.data.manager.class: Xhprof\StoreBundle\Services\ProfilingDataManager

services:
    xhprof.profiling.data.manager:
         class:        "%xhprof.profiling.data.manager.class%"
         calls:
                     - [setContainer, ["@service_container"]]
    xhprof.profiling.save.handler:
             class:        "%xhprof.profiling.save.handler.class%"
             arguments:    ["@xhprof.profiling.data.manager"]