parameters:
#    xhprof_store.example.class: Xhprof\StoreBundle\Example

services:
#    xhprof_store.example:
#        class: %xhprof_store.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
