parameters:
    xhprof.store.profiling.controller.class: Xhprof\StoreBundle\Controller\ProfilingController
    xhprof.profiling.save.handler.class: Xhprof\StoreBundle\Services\ProfilingSaveHandler

services:
    xhprof.store.profiling.controller:
        class: "%xhprof.store.profiling.controller.class%"
    xhprof.profiling.save.handler:
         class:        "%xhprof.profiling.save.handler.class%"
         calls:
                     - [setContainer, ["@service_container"]]
