parameters:
#    xhprof_gui.example.class: Xhprof\GuiBundle\Example

services:
#    xhprof_gui.example:
#        class: %xhprof_gui.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
