parameters:
    xhprof.profiling.save.handler.class: Xhprof\GuiBundle\Services\ProfilingSaveHandler

services:
    xhprof.profiling.save.handler:
         class:        "%xhprof.profiling.save.handler.class%"
         calls:
              - [setDoctrineEntityManager, [@doctrine.orm.entity_manager]]