parameters:
    xhprof.profiling.save.handler.class: Xhprof\GuiBundle\Services\ProfilingSaveHandler

services:
    xhprof.profiling.save.handler:
         class:        "%xhprof.profiling.save.handler.class%"
         calls:
              - [setDoctrine, ["@doctrine"]]
    kernel.listener.number_formatter:
            class: Xhprof\GuiBundle\EventListener\NumberFormatterListener
            calls:
               - [setTwig, ["@twig"]]
            tags:
                - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }